spring:
  main:
    banner-mode: off
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisplus_db?serverTimezone=UTC
    username: root
    password: smile011118

mybatis-plus:
  configuration:
    global-config:
      banner: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


